### ISSUE TITLE
Write a Makefile

### ISSUE THREAD

**Issue by JohnMH** [OpenHMD/OpenHMDDemo#1]
`compile.sh` is horrible, write a Makefile!

In all seriousness, there should be a Makefile, if only for readability. I know that you say this in the README, but there hasn't been any activity in 11 months..

**Comment by TheOnlyJoey** [comment]
I know this is horrible, actually have a CMake file for this project lying around, need to fix it up a bit and commit.

This project will be updated some more soon anyway, have some fixes and optimizations that make it a bit more useful.
Thanks for your interest btw!

**Comment by JohnMH** [comment]
I'd be happy to write an autoconf script for you, so you aren't reliant on CMake.

On February 7, 2016 12:04:54 PM EST, TheOnlyJoey notifications@github.com wrote:

> I know this is horrible, actually have a CMake file for this project
> lying around, need to fix it up a bit and commit.
> 
> This project will be updated some more soon anyway, have some fixes and
> optimizations that make it a bit more useful.
> Thanks for your interest btw!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenHMD/OpenHMDDemo/issues/1#issuecomment-181051410

## 

Sent from my Android device. Please excuse my brevity.

**Comment by TheOnlyJoey** [comment]
I actually prefer CMake over autotools, have introduced this for OpenHMD as
well.
If you want to write a autoconf script, I am happy to include it as
optional compile option, but I will not be maintaining it.

**Comment by TheOnlyJoey** [comment]
Well better later then never! but a CMake project file has been added.
Should be a lot easier and convenient to compile now.
